apiVersion: v2
name: futtertrog
description: A Helm chart for Kubernetes
type: application
version: 1.6.1
appVersion: 21.10.1
home: https://github.com/robjuz/helm-charts/tree/master/charts/futtertrog
sources:
  - https://github.com/robjuz/futtertrog/tree/21.10.1

dependencies:
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
    condition: mariadb.enabled
