include:
  - template: Auto-DevOps.gitlab-ci.yml

test:
  image: thecodingmachine/php:8.1-v4-cli
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
  variables:
    PHP_EXTENSIONS: "intl gmp sqlite3 pdo_sqlite xdebug"
    XDEBUG_MODE: coverage
  services: []
  before_script:
    - composer install
    - cp .env.example .env
    - php artisan key:gen
  script:
    - vendor/bin/phpunit --stop-on-error --coverage-text --coverage-cobertura=coverage.cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml


production:
  variables:
    HELM_RELEASE_NAME: futtertrog
  environment:
    kubernetes:
      namespace: futtertrog

sentry:releases:prepare:
  stage: build
  image: getsentry/sentry-cli
  script:
    - sentry-cli releases new $CI_COMMIT_SHA
    - sentry-cli releases set-commits $CI_COMMIT_SHA --auto
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sentry:releases:deploys:
  stage: performance
  image: getsentry/sentry-cli
  variables:
    GIT_STRATEGY: none
  script:
    - sentry-cli releases finalize $CI_COMMIT_SHA
    - sentry-cli releases deploys $CI_COMMIT_SHA new -e $CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
