include:
  - template: Auto-DevOps.gitlab-ci.yml

test:
  image: thecodingmachine/php:8.1-v4-cli
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
  variables:
    PHP_EXTENSIONS: "intl gmp sqlite3 pdo_sqlite xdebug"
    XDEBUG_MODE: coverage
  services: []
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:gen
    - vendor/bin/phpunit --colors=never --stop-on-error --coverage-text

production_manual:
  variables:
    HELM_RELEASE_NAME: futtertrog
  environment:
    kubernetes:
      namespace: futtertrog

sentry:releases:
  stage: build
  image: getsentry/sentry-cli
  script:
    - sentry-cli releases new $CI_COMMIT_SHA
    - sentry-cli releases set-commits $CI_COMMIT_SHA --auto
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


sentry:releases:staging:
  stage: staging
  image: getsentry/sentry-cli
  variables:
    GIT_STRATEGY: none
  needs:
    - sentry:releases
    - staging
  script:
    - sentry-cli releases finalize $CI_COMMIT_SHA
    - sentry-cli releases deploys $CI_COMMIT_SHA new -e staging
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sentry:releases:production:
  stage: production
  image: getsentry/sentry-cli
  variables:
    GIT_STRATEGY: none
  needs:
    - sentry:releases
    - production_manual
  script:
    - sentry-cli releases finalize $CI_COMMIT_SHA
    - sentry-cli releases deploys $CI_COMMIT_SHA new -e production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
