include:
  - project: 'helmundwalter/ci'
    file: 'Auto-DevOps.yml'
    ref: refactor

test:phpunit:
  variables:
    PHP_EXTENSIONS: "intl gmp sqlite3 pdo_sqlite xdebug"
  services: [ ]
  before_script:
    - composer install
    - cp .env.example .env
    - php artisan key:gen

production:
  variables:
    HELM_RELEASE_NAME: futtertrog
  environment:
    kubernetes:
      namespace: futtertrog
