include:
  - template: Auto-DevOps.gitlab-ci.yml

test:
  image: thecodingmachine/php:7.4-v4-cli
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
  variables:
    PHP_EXTENSIONS: "intl gmp sqlite3 pdo_sqlite xdebug"
    XDEBUG_MODE: coverage
  services: []
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:gen
    - vendor/bin/phpunit --colors=never --stop-on-error --coverage-text

production_manual:
  variables:
    HELM_RELEASE_NAME: futtertrog
  environment:
    kubernetes:
      namespace: futtertrog
