language: php

php:
  - 7.2
  
services:
  - mysql
  
dist: xenial

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test; set innodb_lock_wait_timeout=100;'

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  
  
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - vendor
