language: php

php:
  - 7.2

dist: xenial

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt install php7.2-sqlite3


before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/codacycoverage clover coverage.xml

cache:
  apt: true
  directories:
    - vendor