language: php

php:
  - 7.2

dist: osx

#before_install:
#  - sudo apt remove sqlite3 -y
#  - wget https://www.sqlite.org/2019/sqlite-autoconf-3270200.tar.gz
#  - tar -zxvf sqlite-autoconf-3270200.tar.gz
#  - cd sqlite-autoconf-3270200
#  - ./configure
#  - make -DSQLITE_ENABLE_JSON1
#  - sudo make install


before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/codacycoverage clover coverage.xml

cache:
  directories:
    - vendor