language: php

php:
  - 7.2

dist: xenial

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  
  
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - vendor
