language: php

php:
  - 7.2

dist: xenial

before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get install sqlite3

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  
  
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - vendor
