version: '3'

services:
  futtertrog:
    image: thecodingmachine/php:7.3-v4-apache
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - db
    environment:
      DB_DATABASE: futtertrog
      DB_USERNAME: futtertrog
      DB_PASSWORD: futtertrog

      APACHE_DOCUMENT_ROOT: public/

      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_GMP: 1
      PHP_EXTENSION_SQLITE3: 1
      PHP_EXTENSION_PDO_SQLITE: 1

      STARTUP_COMMAND_1: composer install
      STARTUP_COMMAND_2: php artisan migrate --force

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: futtertrog
      MYSQL_USER: futtertrog
      MYSQL_PASSWORD: futtertrog
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
