version: '3.8'

services:
  app:
    image: thecodingmachine/php:7.4-v4-apache
    ports:
      - ${APP_PORT:-8080}:80
    volumes:
      - ./:/var/www/html
      - ./storage/code-coverage:/opt/phpstorm-coverage
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      APACHE_DOCUMENT_ROOT: public/

      PHP_EXTENSIONS: "intl gmp sqlite3 pdo_sqlite xdebug"

      PHP_INI_MEMORY_LIMIT: 100M

      STARTUP_COMMAND_1: php -r "file_exists('.env') || copy('.env.example', '.env');"
      STARTUP_COMMAND_2: composer install
      STARTUP_COMMAND_3: php artisan migrate --force

      CRON_SCHEDULE: "* * * * *"
      CRON_COMMAND: php artisan schedule:run

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: futtertrog
      MYSQL_USER: futtertrog
      MYSQL_PASSWORD: futtertrog
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin -ufuttertrog -pfuttertrog status
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025 # smtp
      - 8025 # webUI

volumes:
  mysql:
