version: '3'

services:
  web:
      build: ./
      ports:
          - 8001:80
      volumes:
          - ./:/var/www
      links:
          - db
      environment:
          DB_HOST: db
          DB_DATABASE: futtertrog
          DB_USERNAME: futtertrog
          DB_PASSWORD: futter-4z5n9wz4-trog
          DB_CONNECTION: mysql
  db:
      image: mariadb
      environment:
          MYSQL_DATABASE: futtertrog
          MYSQL_USER: futtertrog
          MYSQL_PASSWORD: futter-4z5n9wz4-trog
          MYSQL_RANDOM_ROOT_PASSWORD: 1
