version: '3'

services:
  futtertrog:
    container_name: futtertrog
    image: thecodingmachine/php:7.4-v4-apache
    ports:
      - ${APP_PORT:-8080}:80
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      APACHE_DOCUMENT_ROOT: public/

      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_GMP: 1
      PHP_EXTENSION_SQLITE3: 1
      PHP_EXTENSION_PDO_SQLITE: 1

      PHP_INI_MEMORY_LIMIT: 100M

      STARTUP_COMMAND_1: composer install
      STARTUP_COMMAND_2: php artisan migrate --force

      CRON_SCHEDULE: "* * * * *"
      CRON_COMMAND: php artisan schedule:run

  db:
    container_name: futtertrog_db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: futtertrog
      MYSQL_USER: futtertrog
      MYSQL_PASSWORD: futtertrog
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin -ufuttertrog -pfuttertrog status
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3


  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"


volumes:
  mysql:
    driver: local
