{{- if and .Values.adminName .Values.adminEmail .Values.adminPassword }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-crate-admin
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "20"
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}-config
            - secretRef:
                name: {{ include "common.names.fullname" . }}-basic-secret
          {{- if .Values.application.secretName }}
            - secretRef:
                name: {{ .Values.application.secretName }}
          {{- end }}
          command:
            - php
            - artisan
            - futtertrog:create-admin
            - -n
            - {{ .Values.adminName }}
            - {{ .Values.adminEmail }}
            - {{ .Values.adminPassword }}
      restartPolicy: OnFailure
{{- end }}
