apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-db-migrate
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      {{- with .Values.image.secrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}-config
            - secretRef:
                name: {{ include "common.names.fullname" . }}-basic-secret
          {{- if .Values.application.secretName }}
            - secretRef:
                name: {{ .Values.application.secretName }}
          {{- end }}
          command:
            - php
            - artisan
            - migrate
            - --force
      restartPolicy: OnFailure
